import = [
    "/Users/jfairbanks/.config/alacritty/themes/themes/solarized_dark.toml",
]

live_config_reload = true

[shell]
program = "zsh"
args = ["-l"]

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.90
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 18
y = 16

[scrolling]
history=10000

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.offset]
x = 0
y = 1

[selection]
save_to_clipboard = true

[keyboard]

bindings= [
    # { key = "r", chars = "S" },
    # { key = "End", action = "Last" },
    # { key = "f", chars = "q" }
    { key = "Left", mods = "Control", action = "WordLeft" },
    { key = "Right", mods = "Control", chars = "\u001BF" }
]
